# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WakeUp!' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WakeUp!

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  
  # Rx Extensions
  pod 'RxFlow'
  pod 'RxGesture'
  pod 'RxDataSources'
  pod 'NSObject+Rx'

  # Networking
  pod 'Moya/RxSwift'
  
  # Tools
  pod 'R.swift'
  pod 'Reusable'
  
  # Image
  pod 'Kingfisher'
  
  # DataBase
  pod 'RealmSwift'
  
  # Security
  pod 'KeychainAccess'
  pod 'CryptoSwift'

  # UI
  pod 'NVActivityIndicatorView/Extended'
  pod 'SwiftMessages'
  pod 'ImageSlideshow/Kingfisher'
  pod 'KafkaRefresh'
  
  # Code Quality
  pod 'FLEX'

  # WebRTC
  pod 'RemoteMonster', '~> 2.7.0'

end
